In [1]:
import pandas as pd
import numpy as np

In [2]:
r_e = 2.817e-15
c = 3e8
n = 6.9e10
e = 1.6e-19
q=n*e
E_e = 500
mc2 = 0.511
gamma = E_e/mc2
pi = 3.1416
C = 171.7
sigma_s = 0.025
gamma

978.4735812133072

In [3]:
A = r_e*r_e*c*q/(8*pi*e*gamma*gamma*gamma*sigma_s*C)
A

1.6253449556498956e-21

In [4]:
df_ = pd.read_csv("tp0.txt",delim_whitespace=True)
s = df_['s']
df_ = (s - np.roll(s, 1))[1:]# second row - first row, 1: removes the first row at the end
df_.reset_index(drop = True, inplace=True)
df_
df0 = pd.DataFrame(df_) #Converting into dataframe
df0

        s
0    1.40
1    0.25
2    2.90
3    0.25
4    2.90
..    ...
166  2.90
167  0.25
168  2.90
169  0.25
170  1.40

[171 rows x 1 columns]

In [5]:
# Load all twiss parameters and momentum aperture
df1=pd.read_csv("tp3.txt",sep="\s+")
df2=pd.read_csv("tp4.txt",sep="\s+")
df3=pd.read_csv("ma3.txt",sep="\s+")

In [6]:
# Merge df1 df2 and df3
df4 = df0.reset_index().merge(df1.reset_index(), left_index=True, right_index=True, how='left')
df5 = df2.reset_index().merge(df3.reset_index(), left_index=True, right_index=True, how='left')
df = df4.reset_index().merge(df5.reset_index(), left_index=True, right_index=True, how='left')

In [7]:
df

,index_x,index_x_x,s,index_y_x,bx,ax,by,ay,sigx1,sigy,gx,index_y,index_x_y,etx,etxp,index_y_y,dPos,dNeg
0,0,0,1.40,0,8.568533,-1.680000e-01,8.568533,-1.680000e-01,0.000006,0.000529,0.120000,0,0,-1.752308e-09,-1.656788e-10,0,0.002983,-0.002126
1,1,1,0.25,1,8.432154,7.086640e-01,8.891986,-1.137285e+00,0.000005,0.000538,0.178152,1,1,-1.770246e-09,2.249035e-11,1,0.002990,-0.002140
2,2,2,2.90,2,5.820160,1.920233e-01,17.657340,-1.885252e+00,0.000004,0.000759,0.178152,2,2,-1.705024e-09,2.249035e-11,2,0.002987,-0.002140
3,3,3,0.25,3,5.794598,-8.942557e-02,18.429010,-1.190829e+00,0.000004,0.000775,0.173955,3,3,-1.708149e-09,-4.750658e-11,3,0.002986,-0.002130
4,4,4,2.90,4,7.776225,-5.938939e-01,26.439290,-1.571338e+00,0.000005,0.000928,0.173955,4,4,-1.845918e-09,-4.750658e-11,4,0.002983,-0.002130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,166,166,2.90,166,5.794598,8.942557e-02,18.429010,1.190829e+00,0.000004,0.000775,0.173955,166,166,-1.708155e-09,4.750557e-11,166,0.002894,-0.002154
167,167,167,0.25,167,5.820160,-1.920233e-01,17.657340,1.885252e+00,0.000004,0.000759,0.178152,167,167,-1.705031e-09,-2.249162e-11,167,0.002894,-0.002154
168,168,168,2.90,168,8.432154,-7.086640e-01,8.891986,1.137285e+00,0.000005,0.000538,0.178152,168,168,-1.770256e-09,-2.249162e-11,168,0.002894,-0.002154
169,169,169,0.25,169,8.568533,1.680000e-01,8.568533,1.680000e-01,0.000006,0.000529,0.120000,169,169,-1.752318e-09,1.656786e-10,169,0.002908,-0.002097
170,170,170,1.40,170,8.333333,8.179850e-09,8.333333,-1.807162e-09,0.000005,0.000521,0.120000,170,170,-1.520368e-09,1.656786e-10,170,0.002891,-0.002097

In [8]:
sig_d = 2.076E-04
sig_d_sq = sig_d*sig_d

In [9]:
for ind, row in df.iterrows():
    df.loc[ind,"etx_del_sq"] = sig_d_sq * (row["etx"]*row["etx"])
for ind, row in df.iterrows():
    df.loc[ind,"sigx"] = np.sqrt(row["sigx1"] + row["etx_del_sq"])

In [10]:
df

,index_x,index_x_x,s,index_y_x,bx,ax,by,ay,sigx1,sigy,gx,index_y,index_x_y,etx,etxp,index_y_y,dPos,dNeg,etx_del_sq,sigx
0,0,0,1.40,0,8.568533,-1.680000e-01,8.568533,-1.680000e-01,0.000006,0.000529,0.120000,0,0,-1.752308e-09,-1.656788e-10,0,0.002983,-0.002126,1.323353e-25,0.002364
1,1,1,0.25,1,8.432154,7.086640e-01,8.891986,-1.137285e+00,0.000005,0.000538,0.178152,1,1,-1.770246e-09,2.249035e-11,1,0.002990,-0.002140,1.350585e-25,0.002345
2,2,2,2.90,2,5.820160,1.920233e-01,17.657340,-1.885252e+00,0.000004,0.000759,0.178152,2,2,-1.705024e-09,2.249035e-11,2,0.002987,-0.002140,1.252898e-25,0.001948
3,3,3,0.25,3,5.794598,-8.942557e-02,18.429010,-1.190829e+00,0.000004,0.000775,0.173955,3,3,-1.708149e-09,-4.750658e-11,3,0.002986,-0.002130,1.257495e-25,0.001944
4,4,4,2.90,4,7.776225,-5.938939e-01,26.439290,-1.571338e+00,0.000005,0.000928,0.173955,4,4,-1.845918e-09,-4.750658e-11,4,0.002983,-0.002130,1.468519e-25,0.002252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,166,166,2.90,166,5.794598,8.942557e-02,18.429010,1.190829e+00,0.000004,0.000775,0.173955,166,166,-1.708155e-09,4.750557e-11,166,0.002894,-0.002154,1.257504e-25,0.001944
167,167,167,0.25,167,5.820160,-1.920233e-01,17.657340,1.885252e+00,0.000004,0.000759,0.178152,167,167,-1.705031e-09,-2.249162e-11,167,0.002894,-0.002154,1.252908e-25,0.001948
168,168,168,2.90,168,8.432154,-7.086640e-01,8.891986,1.137285e+00,0.000005,0.000538,0.178152,168,168,-1.770256e-09,-2.249162e-11,168,0.002894,-0.002154,1.350600e-25,0.002345
169,169,169,0.25,169,8.568533,1.680000e-01,8.568533,1.680000e-01,0.000006,0.000529,0.120000,169,169,-1.752318e-09,1.656786e-10,169,0.002908,-0.002097,1.323368e-25,0.002364
170,170,170,1.40,170,8.333333,8.179850e-09,8.333333,-1.807162e-09,0.000005,0.000521,0.120000,170,170,-1.520368e-09,1.656786e-10,170,0.002891,-0.002097,9.962128e-26,0.002331

In [11]:
for ind, row in df.iterrows():
    df.loc[ind,"H(s)"] = (row["gx"]*row["etx"]*row["etx"]) + (2* row["ax"]*row["etx"]*row["etxp"]) + (row["bx"]*row["etxp"]*row["etxp"])

In [13]:
ex = 0.652e-06
sig_d = 2.076E-04
sig_d_sq = sig_d*sig_d
ratio = sig_d_sq / ex
for ind, row in df.iterrows():
    df.loc[ind,"sig_div"] = (ex /row["sigx"])*np.sqrt(1 + (row["H(s)"]*ratio))

In [14]:
gamma_H = 978.47
for ind, row in df.iterrows():
    df.loc[ind,"denom"] = row["sig_div"]*gamma_H
    
for ind, row in df.iterrows():
    df.loc[ind,"x"] = (row["dPos"]/row["denom"])*(row["dPos"]/row["denom"])

In [15]:
# Integrating F(x) and getting array values of integration for all values of x
from scipy.integrate import quad
import math
from math import log
x_values = df["x"].to_numpy()
I1 = np.empty(len(x_values))
def f(u,x):
    return (1/u - 0.5*np.log(1/u) - 1)*np.exp(-x/u)
for i, x in enumerate(x_values):
    I1[i] = quad(f, 0, 1, args=(x))[0]
I1

array([6.93743782, 6.94836906, 7.32020822, 7.32521912, 7.03359991,
       6.9820753 , 5.74937353, 5.68191708, 6.27800986, 6.32918206,
       6.53975907, 6.56968978, 7.50598908, 7.47076321, 7.2236784 ,
       7.17645069, 6.88979705, 6.90941264, 7.35746558, 7.98896477,
       8.4641181 , 8.44370621, 7.82918276, 7.42384239, 6.96638629,
       6.96357907, 7.39194229, 7.88929159, 8.43704075, 8.42083508,
       8.32147473, 8.21411018, 7.87309515, 7.59773672, 7.35642442,
       7.35539897, 7.4055597 , 7.45502849, 7.59671083, 7.86513308,
       8.41297418, 8.41258155, 8.21474366, 8.20584342, 7.8648316 ,
       7.16268022, 6.9215914 , 6.93428846, 6.98440067, 7.03382348,
       7.15464366, 7.6723826 , 8.22015846, 8.23280848, 7.68498974,
       7.39125542, 6.96571217, 6.97478062, 7.43831715, 7.84539971,
       8.46193979, 8.45597374, 7.97541059, 7.42189126, 6.97377174,
       6.95887353, 7.17588117, 7.27083273, 7.51794096, 7.47645782,
       6.73275727, 6.72865825, 6.98390452, 6.97476917, 6.61726558,
       6.62676881, 7.1509801 , 7.15051198, 6.62698649, 6.64555055,
       7.83277118, 7.83209412, 6.62686157, 6.62665066, 7.83187989,
       7.83712516, 6.62482232, 6.62682198, 7.82815479, 7.82877516,
       6.62661722, 6.63525627, 7.15879079, 7.1504283 , 6.62619736,
       6.61680858, 6.97403612, 6.98317164, 6.72793139, 6.75787714,
       7.47638799, 7.50238812, 7.25528798, 7.16311005, 6.94555295,
       6.97458835, 7.4227087 , 7.97139398, 8.46416106, 8.48493384,
       7.87769163, 7.39122589, 6.92773138, 6.91002895, 7.33833862,
       7.67950389, 8.2271236 , 8.23067067, 8.12985621, 8.0239842 ,
       7.68304858, 7.18954257, 6.94843879, 6.94459778, 6.99545459,
       7.04487881, 7.1864428 , 7.8789832 , 8.4267265 , 8.43659222,
       8.33723101, 8.2294947 , 7.88847376, 7.63081925, 7.38949285,
       7.39666682, 7.44683148, 7.49052384, 7.63226613, 7.92598606,
       8.47375647, 8.45964618, 7.91188436, 7.40228835, 6.97363995,
       7.01868573, 7.4822744 , 7.84537854, 8.49768803, 8.52663925,
       8.05145758, 7.46031002, 7.01215239, 6.99359483, 7.2111777 ,
       7.27929057, 7.52641172, 7.53435496, 6.65929337, 6.52795814,
       6.31739539, 6.27800986, 5.77041653, 5.77294572, 7.00572573,
       7.0942767 , 7.38764529, 7.38325378, 7.01354406, 6.98793008,
       7.0274827 ])

In [19]:
for ind, row in df.iterrows():
    df.loc[ind,"dPos_sq"] = row["dPos"]*row["dPos"]
for ind, row in df.iterrows():
    df.loc[ind,"I2"] = row["sigx"]*row["sigy"]*row["sig_div"]*row["dPos_sq"]

In [20]:
df["I1"] = pd.Series(I1) # Convert numpy array into dataframe column

In [22]:
for ind, row in df.iterrows():
    df.loc[ind,"I"] = (row["I1"] / row["I2"])*row["s"]
    
I_sum = df["I"].sum()
print(I_sum)

5.0489675230181786e+17

In [23]:
pos_trate = A*I_sum
pos_tlifetime = 1/(pos_trate)
pos_lifetime = pos_tlifetime/3600
pos_lifetime

0.3384927524580157

### Touscheck Rate for delta_negative

In [24]:
gamma_H = 978.47
for ind, row in df.iterrows():
    df.loc[ind,"denom"] = row["sig_div"]*gamma_H
    
for ind, row in df.iterrows():
    df.loc[ind,"y"] = (row["dNeg"]/row["denom"])*(row["dNeg"]/row["denom"])

In [27]:
from scipy.integrate import quad
import math
from math import log
y_values = df["y"].to_numpy()
I1y = np.empty(len(y_values))
def f(u,y):
    return (1/u - 0.5*np.log(1/u) - 1)*np.exp(-y/u)
for i, y in enumerate(y_values):
    I1y[i] = quad(f, 0, 1, args=(y))[0]
I1y

array([7.61282048, 7.61570025, 7.98580622, 7.99975499, 7.70607925,
       7.61636185, 6.38094627, 6.35268604, 6.95062448, 6.99963634,
       7.21065919, 7.24293637, 8.11900821, 8.11169073, 7.86436012,
       7.71026501, 7.49246482, 7.52557188, 7.97414083, 8.40994736,
       8.88526631, 8.89591361, 8.28708983, 7.85133138, 7.38911595,
       7.44197512, 7.87073112, 8.26834436, 8.81627793, 8.81076283,
       8.71137478, 8.59054863, 8.24940841, 7.88916363, 7.64773915,
       7.66385765, 7.71273288, 7.74340284, 7.90480076, 8.23610498,
       8.78402219, 8.77666592, 8.68854155, 8.58857018, 8.24000744,
       7.938894  , 7.69737673, 7.67836927, 7.72855757, 7.77805248,
       7.91980407, 8.27542322, 8.82335972, 8.81342486, 8.23996149,
       7.78886345, 7.36062447, 7.39062158, 7.85453207, 8.27253693,
       8.88003683, 8.89768395, 8.42236092, 7.82014592, 7.49229768,
       7.47228562, 7.69018372, 7.89276912, 8.14010794, 8.06451522,
       7.34521162, 7.36447033, 7.62008601, 7.56051992, 7.20249869,
       7.24643194, 7.77041791, 7.7428025 , 7.2185679 , 7.2462779 ,
       8.45284134, 8.45359847, 7.24703191, 7.2482886 , 8.45485538,
       8.45468326, 7.24811676, 7.24742582, 8.45284134, 8.47040291,
       7.26381057, 7.21861299, 7.74284763, 7.77889465, 7.25392479,
       7.20249869, 7.56051992, 7.62054664, 7.3649411 , 7.3941184 ,
       8.06756889, 8.14496314, 7.89871963, 7.66704342, 7.44925966,
       7.42442707, 7.87292786, 8.37070263, 8.86085714, 8.81710878,
       8.20967927, 7.88292795, 7.41899761, 7.4177515 , 7.84649499,
       8.26625923, 8.81419194, 8.81106466, 8.7130106 , 8.60606719,
       8.26492259, 7.91722422, 7.68957387, 7.68775226, 7.73890785,
       7.78839875, 7.93015227, 8.25679664, 8.8047254 , 8.8066424 ,
       8.70725413, 8.59003217, 8.24889208, 7.95987802, 7.69102231,
       7.68135196, 7.73153386, 7.78188954, 7.92193968, 8.27043452,
       8.81837277, 8.80678352, 8.2588539 , 7.82485104, 7.39613003,
       7.39351088, 7.8574233 , 8.32837213, 8.8966358 , 8.93755936,
       8.45093017, 7.99231603, 7.54563762, 7.51331745, 7.73109765,
       7.86140777, 8.10873751, 8.14976036, 7.27364643, 7.23408156,
       7.02304881, 6.92287578, 6.32499582, 6.31510427, 7.55029442,
       7.68329605, 7.97696286, 7.97256183, 7.60246267, 7.64029345,
       7.66807441])

In [28]:
for ind, row in df.iterrows():
    df.loc[ind,"dNeg_sq"] = row["dNeg"]*row["dNeg"]
for ind, row in df.iterrows():
    df.loc[ind,"I2y"] = row["sigx"]*row["sigy"]*row["sig_div"]*row["dNeg_sq"]

In [30]:
df["I1y"] = pd.Series(I1y) # Convert numpy array into dataframe column

In [31]:
for ind, row in df.iterrows():
    df.loc[ind,"Iy"] = (row["I1y"]/ row["I2y"])*row["s"] # total integration = numerator divide by denominator

In [32]:
Iy_sum = df["Iy"].sum()
print(Iy_sum)

9.249742682704855e+17

In [33]:
neg_trate = A*Iy_sum
neg_tlifetime = 1/(neg_trate)
neg_lifetime = neg_tlifetime/3600
neg_lifetime

0.18476610350827483

Elegant user forum suggests the following way to calculate the Touschek lifetime using deltaNegative and deltaPositive [touschek](https://www3.aps.anl.gov/forums/elegant/viewtopic.php?f=14&t=424&p=1672&hilit=Momentum+aperture+and+touschek+scattering#p1680)

Using this formalism to calculate the Touschek lifetime, we calculate negative lifetime and positive lifetime for the negative and positive momentum aperture values respectively. $ \frac{1}{\tau} = \frac{1}{2* lifetime_{neg}} + \frac{1}{2*lifetime_{pos}}$

In [34]:
t_rate = (1/(2*pos_lifetime))+(1/(2*neg_lifetime))
t_rate

4.183260570930891

In [35]:
tlifetime = 1/t_rate
tlifetime

0.23904798255908608